<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 12px; color: #1F2937; }
        h1 { font-size: 18px; color: #0A3D62; margin-bottom: 2px; }
        .sub { color: #6B7280; font-size: 11px; margin-bottom: 20px; }
        table { width: 100%; border-collapse: collapse; margin-top: 16px; }
        td, th { border: 1px solid #D1D5DB; padding: 8px; text-align: left; }
        th { background: #F3F4F6; }
        .label { color: #6B7280; }
        .total td { font-weight: bold; background: #F9FAFB; }
        .footer { margin-top: 30px; font-size: 10px; color: #6B7280; border-top: 1px solid #D1D5DB; padding-top: 10px; }
        .stamp { margin-top: 24px; font-size: 11px; }
    </style>
</head>
<body>
    <h1>{{ $tenantName }}</h1>
    <div class="sub">Driving School - License Hours Report</div>

    <table>
        <tr><td class="label" style="width:40%">Student</td><td>{{ $student->name }}</td></tr>
        <tr><td class="label">Report generated</td><td>{{ $generatedAt }}</td></tr>
        <tr><td class="label">Validated by</td><td>{{ $validatedByName }}</td></tr>
        <tr><td class="label">Validated on</td><td>{{ $validatedAt }}</td></tr>
    </table>

    <table>
        <tr>
            <th>Hours type</th>
            <th>Completed</th>
            @if ($requiredTheory > 0 || $requiredPractical > 0)
                <th>Required</th>
            @endif
        </tr>
        <tr>
            <td>Theory</td>
            <td>{{ intdiv($theoryMinutes, 60) }}h {{ $theoryMinutes % 60 }}m</td>
            @if ($requiredTheory > 0 || $requiredPractical > 0)
                <td>{{ $requiredTheory > 0 ? intdiv($requiredTheory,60).'h '.($requiredTheory%60).'m' : '-' }}</td>
            @endif
        </tr>
        <tr>
            <td>Practical</td>
            <td>{{ intdiv($practicalMinutes, 60) }}h {{ $practicalMinutes % 60 }}m</td>
            @if ($requiredTheory > 0 || $requiredPractical > 0)
                <td>{{ $requiredPractical > 0 ? intdiv($requiredPractical,60).'h '.($requiredPractical%60).'m' : '-' }}</td>
            @endif
        </tr>
        <tr class="total">
            <td>Total</td>
            <td>{{ intdiv($theoryMinutes + $practicalMinutes, 60) }}h {{ ($theoryMinutes + $practicalMinutes) % 60 }}m</td>
            @if ($requiredTheory > 0 || $requiredPractical > 0)
                <td></td>
            @endif
        </tr>
    </table>

    <div class="stamp">
        This report reflects hours recorded in {{ $tenantName }}'s DriveCM system and validated by
        the school on {{ $validatedAt }}. The figures are the hours as validated; the school is
        responsible for their accuracy and for submission to the Ministry of Transport.
    </div>

    <div class="footer">
        Generated by DriveCM on {{ $generatedAt }} - Document reference: VR-{{ $validationId }}
    </div>
</body>
</html>